[{
    "_id": 25655346,
    "title": "How the placenta evolved from an ancient virus",
    "points": 34,
    "user": "_Microft",
    "time": 1609917195,
    "time_ago": "2 hours ago",
    "comments_count": 3,
    "type": "link",
    "url": "https://whyy.org/segments/the-placenta-went-viral-and-protomammals-were-born/",
    "domain": "whyy.org"
  },
  {
    "_id": 25654504,
    "title": "We Built a Facebook Inspector",
    "points": 135,
    "user": "atg_abhishek",
    "time": 1609905233,
    "time_ago": "5 hours ago",
    "comments_count": 28,
    "type": "link",
    "url": "https://themarkup.org/citizen-browser/2021/01/05/how-we-built-a-facebook-inspector",
    "domain": "themarkup.org"
  },
  {
    "_id": 25649557,
    "title": "DALL·E: Creating Images from Text",
    "points": 906,
    "user": "todsacerdoti",
    "time": 1609873701,
    "time_ago": "14 hours ago",
    "comments_count": 179,
    "type": "link",
    "url": "https://openai.com/blog/dall-e/",
    "domain": "openai.com"
  },




  {
    "_id": 25655066,
    "title": "US doctor forgives $650k in medical bills for cancer patients",
    "points": 114,
    "user": "williamsharris",
    "time": 1609913616,
    "time_ago": "3 hours ago",
    "comments_count": 103,
    "type": "link",
    "url": "https://www.bbc.com/news/world-us-canada-55544496",
    "domain": "bbc.com"
  },
  {
    "_id": 25654118,
    "title": "Deep-learning text-to-speech tool for generating voices of various characters",
    "points": 138,
    "user": "clxxx",
    "time": 1609900584,
    "time_ago": "7 hours ago",
    "comments_count": 46,
    "type": "link",
    "url": "https://15.ai/",
    "domain": "15.ai"
  },
  {
    "_id": 25655423,
    "title": "Jim Keller moves to AI chip startup",
    "points": 25,
    "user": "vnorilo",
    "time": 1609918206,
    "time_ago": "2 hours ago",
    "comments_count": 7,
    "type": "link",
    "url": "https://www.reuters.com/article/tenstorrent-tech/moves-former-intel-tesla-chip-exec-jim-keller-joins-artificial-intelligence-startup-idUSL1N2JG2I6",
    "domain": "reuters.com"
  },
  {
    "_id": 25654316,
    "title": "An Uncommon Cold",
    "points": 110,
    "user": "js2",
    "time": 1609902670,
    "time_ago": "6 hours ago",
    "comments_count": 71,
    "type": "link",
    "url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7252012/",
    "domain": "ncbi.nlm.nih.gov"
  },
  {
    "_id": 25649719,
    "title": "Asahi Linux: Linux on Apple Silicon project",
    "points": 533,
    "user": "jackhalford",
    "time": 1609874297,
    "time_ago": "14 hours ago",
    "comments_count": 323,
    "type": "link",
    "url": "https://asahilinux.org/",
    "domain": "asahilinux.org"
  },
  {
    "_id": 25648585,
    "title": "GitHub is fully available in Iran",
    "points": 1466,
    "user": "todsacerdoti",
    "time": 1609869697,
    "time_ago": "15 hours ago",
    "comments_count": 420,
    "type": "link",
    "url": "https://github.blog/2021-01-05-advancing-developer-freedom-github-is-fully-available-in-iran/",
    "domain": "github.blog"
  },
  {
    "_id": 25651103,
    "title": "5G Advocates Renew Attempts to Poach Wi-Fi’s 6GHz Spectrum",
    "points": 200,
    "user": "danaos",
    "time": 1609881071,
    "time_ago": "12 hours ago",
    "comments_count": 120,
    "type": "link",
    "url": "https://www.eetimes.com/5g-advocates-renew-attempts-to-poach-wi-fis-6ghz-spectrum/",
    "domain": "eetimes.com"
  },
  {
    "_id": 25655288,
    "title": "Turing Labs Inc. (YC W20) Is Hiring",
    "points": null,
    "user": null,
    "time": 1609916401,
    "time_ago": "2 hours ago",
    "comments_count": 0,
    "type": "job",
    "url": "https://www.workatastartup.com/jobs/21272",
    "domain": "workatastartup.com"
  },
  {
    "_id": 25644475,
    "title": "Show HN: Cmap – interactive visualization library for concept map",
    "points": 21,
    "user": "rlv04343",
    "time": 1609846710,
    "time_ago": "a day ago",
    "comments_count": 0,
    "type": "link",
    "url": "https://github.com/ionstage/cmap",
    "domain": "github.com"
  },
  {
    "_id": 25652369,
    "title": "Why Learn Prolog in 2021?",
    "points": 173,
    "user": "triska",
    "time": 1609887290,
    "time_ago": "10 hours ago",
    "comments_count": 113,
    "type": "link",
    "url": "http://dstrohmaier.com/why-learn-prolog-in-2021/",
    "domain": "dstrohmaier.com"
  },
  {
    "_id": 25650094,
    "title": "Amazon buys 11 Boeing 767s to expand its cargo fleet",
    "points": 202,
    "user": "seryoiupfurds",
    "time": 1609876194,
    "time_ago": "13 hours ago",
    "comments_count": 157,
    "type": "link",
    "url": "https://www.cbc.ca/news/business/amazon-westjet-1.5861635",
    "domain": "cbc.ca"
  },
  {
    "_id": 25649476,
    "title": "Wasmer 1.0",
    "points": 297,
    "user": "wiqar",
    "time": 1609873321,
    "time_ago": "14 hours ago",
    "comments_count": 116,
    "type": "link",
    "url": "https://medium.com/wasmer/wasmer-1-0-3f86ca18c043",
    "domain": "medium.com"
  },
  {
    "_id": 25651942,
    "title": "27th International Obfuscated C Code Contest winners published",
    "points": 149,
    "user": "beagle3",
    "time": 1609884975,
    "time_ago": "11 hours ago",
    "comments_count": 25,
    "type": "link",
    "url": "https://www.ioccc.org/2020/",
    "domain": "ioccc.org"
  },
  {
    "_id": 25654948,
    "title": "DOSBox-X: Free, cross-platform and complete DOS, Windows 3.x and 9x emulation",
    "points": 22,
    "user": "FlyMoreRockets",
    "time": 1609911645,
    "time_ago": "4 hours ago",
    "comments_count": 2,
    "type": "link",
    "url": "https://dosbox-x.com/",
    "domain": "dosbox-x.com"
  },
  {
    "_id": 25654733,
    "title": "Lunar Programming Language (2018)",
    "points": 29,
    "user": "rottc0dd",
    "time": 1609908255,
    "time_ago": "5 hours ago",
    "comments_count": 4,
    "type": "link",
    "url": "http://users.rcn.com/david-moon/Lunar/",
    "domain": "users.rcn.com"
  },
  {
    "_id": 25650224,
    "title": "Ask HN: Please share your experience teaching your kids to program",
    "points": 222,
    "user": "lmilcin",
    "time": 1609876742,
    "time_ago": "13 hours ago",
    "comments_count": 174,
    "type": "ask",
    "url": "item?id=25650224"
  },
  {
    "_id": 25649091,
    "title": "Is Everything Securities Fraud?",
    "points": 181,
    "user": "Tomte",
    "time": 1609871765,
    "time_ago": "15 hours ago",
    "comments_count": 89,
    "type": "link",
    "url": "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3664132",
    "domain": "papers.ssrn.com"
  },
  {
    "_id": 25652865,
    "title": "Show HN: Build your own programming language in C++",
    "points": 71,
    "user": "codr7",
    "time": 1609890072,
    "time_ago": "10 hours ago",
    "comments_count": 13,
    "type": "link",
    "url": "https://github.com/codr7/alang",
    "domain": "github.com"
  },
  {
    "_id": 25655581,
    "title": "Syntropy Stack – The Future of Programmable Networking",
    "points": 7,
    "user": "rutekit",
    "time": 1609920123,
    "time_ago": "an hour ago",
    "comments_count": 2,
    "type": "link",
    "url": "https://www.syntropystack.com/",
    "domain": "syntropystack.com"
  },
  {
    "_id": 25642935,
    "title": "The Grammar of Frames",
    "points": 7,
    "user": "dvaun",
    "time": 1609830251,
    "time_ago": "a day ago",
    "comments_count": 4,
    "type": "link",
    "url": "https://www.thegrammarof.com/",
    "domain": "thegrammarof.com"
  },
  {
    "_id": 25642728,
    "title": "Locust – Open-source Load Testing Tool",
    "points": 55,
    "user": "dedalus",
    "time": 1609827508,
    "time_ago": "a day ago",
    "comments_count": 10,
    "type": "link",
    "url": "https://locust.io/",
    "domain": "locust.io"
  },
  {
    "_id": 25644194,
    "title": "The Duplication Process",
    "points": 4,
    "user": "lumpy28",
    "time": 1609843962,
    "time_ago": "a day ago",
    "comments_count": 1,
    "type": "link",
    "url": "https://coil.com/p/Lumpy/The-Duplication-Process-Hypothesis/KsIyJ_tLl",
    "domain": "coil.com"
  },
  {
    "_id": 25651871,
    "title": "Kingdom: Sikkim’s merger with India",
    "points": 27,
    "user": "seventyhorses",
    "time": 1609884564,
    "time_ago": "11 hours ago",
    "comments_count": 7,
    "type": "link",
    "url": "https://fiftytwo.in/story/kingdom/",
    "domain": "fiftytwo.in"
  },
  {
    "_id": 25637389,
    "title": "Greenland Sharks",
    "points": 96,
    "user": "longdefeat",
    "time": 1609792044,
    "time_ago": "2 days ago",
    "comments_count": 10,
    "type": "link",
    "url": "https://howtosavetheworld.ca/2020/12/31/several-short-sentences-about-greenland-sharks/",
    "domain": "howtosavetheworld.ca"
  },
  {
    "_id": 25646810,
    "title": "Ticketmaster admits it hacked Songkick before it went out of business",
    "points": 544,
    "user": "cpascal",
    "time": 1609862174,
    "time_ago": "17 hours ago",
    "comments_count": 263,
    "type": "link",
    "url": "https://arstechnica.com/information-technology/2021/01/ticketmaster-pays-10-million-criminal-fine-for-hacking-a-rival-company/",
    "domain": "arstechnica.com"
  },
  {
    "_id": 25650697,
    "title": "Gene Wolfe Turned Science Fiction into High Art (2019)",
    "points": 103,
    "user": "samclemens",
    "time": 1609879106,
    "time_ago": "13 hours ago",
    "comments_count": 94,
    "type": "link",
    "url": "https://www.theringer.com/2019/4/25/18515675/gene-wolfe-science-fiction-author",
    "domain": "theringer.com"
  },
  {
    "_id": 25649740,
    "title": "Clip: Connecting Text and Images",
    "points": 105,
    "user": "sama",
    "time": 1609874375,
    "time_ago": "14 hours ago",
    "comments_count": 8,
    "type": "link",
    "url": "https://openai.com/blog/clip/",
    "domain": "openai.com"
  }
]
